# paths
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
GPIOLIB="$DIR/gpio"
ADG2188_DRIVER="$DIR/../adg2188/adg2188"

# GPIOs on SoC

# GPIOs on expander
GPIO_EXPANDER_BASE=504
ADG2188_RESET_GPIO=$((GPIO_EXPANDER_BASE + 2))
PASSTHROUGH_GPIO=$((GPIO_EXPANDER_BASE + 3))
FOOTSWITCH1_GPIO=$((GPIO_EXPANDER_BASE + 4))
FOOTSWITCH2_GPIO=$((GPIO_EXPANDER_BASE + 6))
FOOTSWITCH3_GPIO=$((GPIO_EXPANDER_BASE + 5))
FOOTSWITCH4_GPIO=$((GPIO_EXPANDER_BASE + 7))

